CREATE TABLE `account_tbl` (
  `CONTACT_ID`    INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` VARCHAR(255),
  PRIMARY KEY (`CONTACT_ID`)
);

CREATE TABLE `order_tbl` (
  `APPLICATION_ID` INT          NOT NULL AUTO_INCREMENT,
  `CONTACT_ID`     INT,
  `DT_CREATED`     DATETIME     NULL,
  `PRODUCT_NAME`   VARCHAR(255) NULL,
  FOREIGN KEY (CONTACT_ID) REFERENCES account_tbl (CONTACT_ID),
  PRIMARY KEY (`APPLICATION_ID`)
);

